INSERT INTO `book` VALUES
    (1,'Unlocking Android','AVAILABLE'),
    (2,'Android in Action, Second Edition','AVAILABLE'),
    (3,'Specification by Example','AVAILABLE'),
    (4,'Flex 3 in Action','AVAILABLE'),
    (5,'Flex 4 in Action','AVAILABLE'),
    (6,'Collective Intelligence in Action','AVAILABLE'),
    (7,'Zend Framework in Action','AVAILABLE'),
    (8,'Flex on Java','AVAILABLE'),
    (9,'Griffon in Action','AVAILABLE'),
    (10,'OSGi in Depth','AVAILABLE'),
    (11,'Flexible Rails','AVAILABLE'),
    (13,'Hello! Flex 4','AVAILABLE'),
    (14,'Coffeehouse','AVAILABLE'),
    (15,'Team Foundation Server 2008 in Action','AVAILABLE'),
    (16,'Brownfield Application Development in .NET','AVAILABLE'),
    (17,'MongoDB in Action','AVAILABLE'),
    (18,'Distributed Application Development with PowerBuilder 6.0','AVAILABLE'),
    (19,'Jaguar Development with PowerBuilder 7','AVAILABLE'),
    (20,'Taming Jaguar','AVAILABLE'),
    (21,'3D User Interfaces with Java 3D','AVAILABLE'),
    (22,'Hibernate in Action','AVAILABLE'),
    (23,'Hibernate in Action (Chinese Edition)','AVAILABLE'),
    (24,'Java Persistence with Hibernate','AVAILABLE'),
    (25,'JSTL in Action','AVAILABLE'),
    (26,'iBATIS in Action','AVAILABLE'),
    (27,'Designing Hard Software','AVAILABLE'),
    (28,'Hibernate Search in Action','AVAILABLE'),
    (29,'jQuery in Action','AVAILABLE'),
    (30,'jQuery in Action, Second Edition','AVAILABLE'),
    (31,'Building Secure and Reliable Network Applications','AVAILABLE'),
    (32,'Ruby for Rails','AVAILABLE'),
    (33,'The Well-Grounded Rubyist','AVAILABLE'),
    (35,'Website Owner''s Manual','AVAILABLE'),
    (36,'ASP.NET 4.0 in Practice','AVAILABLE'),
    (37,'Hello! Python','AVAILABLE'),
    (38,'PFC Programmer''s Reference Manual','AVAILABLE'),
    (39,'Graphics File Formats','AVAILABLE'),
    (40,'Visual Object Oriented Programming','AVAILABLE'),
    (41,'iOS in Practice','AVAILABLE'),
    (42,'iPhone in Action','AVAILABLE'),
    (43,'Silverlight 2 in Action','AVAILABLE'),
    (45,'The Quick Python Book, Second Edition','AVAILABLE'),
    (46,'Internet and Intranet Applications with PowerBuilder 6','AVAILABLE'),
    (48,'Practical Methods for Your Year 2000 Problem','AVAILABLE'),
    (51,'Mobile Agents','AVAILABLE'),
    (52,'Spring Dynamic Modules in Action','AVAILABLE'),
    (53,'SQL Server 2008 Administration in Action','AVAILABLE'),
    (54,'Android in Practice','AVAILABLE'),
    (55,'Object Oriented Perl','AVAILABLE'),
    (56,'GWT in Practice','AVAILABLE'),
    (59,'Ajax in Action','AVAILABLE'),
    (60,'Ajax in Practice','AVAILABLE'),
    (61,'Prototype and Scriptaculous in Action','AVAILABLE'),
    (63,'POJOs in Action','AVAILABLE'),
    (64,'Data Munging with Perl','AVAILABLE'),
    (65,'Hello! HTML5 & CSS3','AVAILABLE'),
    (66,'Seam in Action','AVAILABLE'),
    (67,'Wicket in Action','AVAILABLE'),
    (68,'Open Source SOA','AVAILABLE'),
    (69,'Struts 2 in Action','AVAILABLE'),
    (70,'Essential Guide to Peoplesoft Development and Customization','AVAILABLE'),
    (71,'.NET Multithreading','AVAILABLE'),
    (72,'SCWCD Exam Study Kit Second Edition','AVAILABLE'),
    (73,'Spring Roo in Action','AVAILABLE'),
    (74,'SOA Governance in Action','AVAILABLE'),
    (75,'RSS and Atom in Action','AVAILABLE'),
    (76,'LDAP Programming, Management and Integration','AVAILABLE'),
    (77,'Mule in Action','AVAILABLE'),
    (79,'Java Foundation Classes','AVAILABLE'),
    (117,'Managing Components with Modeler','AVAILABLE'),
    (118,'Command-line Processing with CLI','AVAILABLE'),
    (119,'Understanding and Using Chain','AVAILABLE'),
    (120,'Working with the Logging and Discovery Components','AVAILABLE'),
    (121,'Uploading files with FileUpload','AVAILABLE'),
    (122,'Handling Protocols with the Net Component','AVAILABLE'),
    (123,'XML Parsing with Digester','AVAILABLE'),
    (124,'JXPath and Betwixt: Working with XML','AVAILABLE'),
    (125,'Validating Data with Validator','AVAILABLE'),
    (126,'Enhancing Java Core Libraries with Collections','AVAILABLE'),
    (127,'Enhancing Java Core Libraries with BeanUtils and Lang','AVAILABLE'),
    (128,'Pool and DBCP: Creating and Using Object Pools','AVAILABLE'),
    (129,'Python and Tkinter Programming','AVAILABLE'),
    (130,'Microsoft.NET for Programmers','AVAILABLE'),
    (131,'Grails in Action','AVAILABLE'),
    (132,'Up to Speed with Swing, Second Edition','AVAILABLE'),
    (133,'OSGi in Action','AVAILABLE'),
    (135,'GWT in Action','AVAILABLE'),
    (136,'The Quick Python Book','AVAILABLE'),
    (137,'SharePoint 2010 Site Owner''s Manual','AVAILABLE'),
    (139,'Java Development with Ant','AVAILABLE'),
    (140,'Lucene in Action','AVAILABLE'),
    (141,'Lucene in Action, Second Edition','AVAILABLE'),
    (142,'PowerBuilder 6.0 Questions & Answers','AVAILABLE'),
    (143,'The Awesome Power of PowerJ','AVAILABLE'),
    (144,'The Awesome Power of Power++','AVAILABLE'),
    (145,'Azure in Action','AVAILABLE'),
    (146,'Distributed Agile in Action','AVAILABLE'),
    (147,'Metaprogramming in .NET','AVAILABLE'),
    (148,'Portlets and Apache Portals','AVAILABLE'),
    (149,'Code Generation in Action','AVAILABLE'),
    (150,'Illustrated Guide to HTTP','AVAILABLE'),
    (152,'Agile ALM','AVAILABLE'),
    (153,'Java Network Programming, Second Edition','AVAILABLE'),
    (154,'Struts in Action','AVAILABLE'),
    (155,'Camel in Action','AVAILABLE'),
    (156,'Taming Text','AVAILABLE'),
    (158,'JBoss in Action','AVAILABLE'),
    (159,'Gnuplot in Action','AVAILABLE'),
    (160,'Extending and Embedding Perl','AVAILABLE'),
    (161,'iOS 4 in Action','AVAILABLE'),
    (162,'Elements of Programming with Perl','AVAILABLE'),
    (163,'Learn Windows PowerShell in a Month of Lunches','AVAILABLE'),
    (164,'R in Action','AVAILABLE'),
    (165,'Android in Practice','AVAILABLE'),
    (167,'SOA Security','AVAILABLE'),
    (168,'Rails 3 in Action','AVAILABLE'),
    (169,'Continuous Integration in .NET','AVAILABLE'),
    (170,'Technology Paradise Lost','AVAILABLE'),
    (172,'Kermit 95+','AVAILABLE'),
    (173,'Laszlo in Action','AVAILABLE'),
    (174,'Groovy in Action','AVAILABLE'),
    (175,'Groovy in Action, Second Edition','AVAILABLE'),
    (176,'Object Technology Centers of Excellence','AVAILABLE'),
    (177,'Test Driven','AVAILABLE'),
    (178,'Effective Unit Testing','AVAILABLE'),
    (179,'Making Java Groovy','AVAILABLE'),
    (180,'The Awesome Power of Direct3D/DirectX','AVAILABLE'),
    (181,'Practical Software Requirements','AVAILABLE'),
    (182,'NHibernate in Action','AVAILABLE'),
    (183,'Microsoft Reporting Services in Action','AVAILABLE'),
    (184,'AspectJ in Action','AVAILABLE'),
    (185,'AspectJ in Action, Second Edition','AVAILABLE'),
    (186,'Hadoop in Action','AVAILABLE'),
    (187,'SQR in PeopleSoft and Other Applications','AVAILABLE'),
    (188,'SQR in PeopleSoft and Other Applications, Second Edition','AVAILABLE'),
    (189,'F# in Action','AVAILABLE'),
    (190,'Tuscany SCA in Action','AVAILABLE'),
    (192,'Client/Server Yellow Pages','AVAILABLE'),
    (193,'Object Oriented Application Frameworks','AVAILABLE'),
    (194,'Tapestry in Action','AVAILABLE'),
    (195,'WebWork in Action','AVAILABLE'),
    (196,'MacRuby in Action','AVAILABLE'),
    (197,'Erlang and OTP in Action','AVAILABLE'),
    (198,'SharePoint 2007 Developer''s Guide to Business Data Catalog','AVAILABLE'),
    (199,'Doing IT Right','AVAILABLE'),
    (200,'Adobe AIR in Action','AVAILABLE'),
    (201,'Ant in Action','AVAILABLE'),
    (202,'Restlet in Action','AVAILABLE'),
    (203,'iText in Action','AVAILABLE'),
    (204,'iText in Action, Second Edition','AVAILABLE'),
    (205,'Power-3D','AVAILABLE'),
    (206,'SNA and TCP/IP Enterprise Networking','AVAILABLE'),
    (208,'Subversion in Action','AVAILABLE'),
    (209,'Minimal Perl','AVAILABLE'),
    (210,'Distributed Programming with Java','AVAILABLE'),
    (211,'Comprehensive Networking Glossary and Acronym Guide','AVAILABLE'),
    (212,'JavaServer Faces in Action','AVAILABLE'),
    (213,'LINQ in Action','AVAILABLE'),
    (214,'Internet BBSs','AVAILABLE'),
    (215,'Algorithms of the Intelligent Web','AVAILABLE'),
    (216,'JUnit in Action','AVAILABLE'),
    (217,'Tika in Action','AVAILABLE'),
    (218,'Ruby in Practice','AVAILABLE'),
    (219,'Inside LotusScript','AVAILABLE'),
    (220,'Maximum MIDI','AVAILABLE'),
    (221,'Planning and Managing ATM Networks','AVAILABLE'),
    (222,'Client/Server Applications on ATM Networks','AVAILABLE'),
    (223,'JavaFX in Action','AVAILABLE'),
    (224,'Entity Framework 4 in Action','AVAILABLE'),
    (225,'ASP.NET 2.0 Web Parts in Action','AVAILABLE'),
    (226,'Sass and Compass in Action','AVAILABLE'),
    (227,'Core OWL 5.0','AVAILABLE'),
    (228,'Advanced OWL 5.0','AVAILABLE'),
    (229,'Server-Based Java Programming','AVAILABLE'),
    (230,'SQL Server MVP Deep Dives','AVAILABLE'),
    (231,'SQL Server MVP Deep Dives','AVAILABLE'),
    (232,'SQL Server MVP Deep Dives','AVAILABLE'),
    (233,'PostGIS in Action','AVAILABLE'),
    (235,'Programming Mac OS X','AVAILABLE'),
    (236,'The Art of Unit Testing','AVAILABLE'),
    (237,'Mahout in Action','AVAILABLE'),
    (238,'ASP.NET MVC in Action','AVAILABLE'),
    (239,'ASP.NET MVC 2 in Action','AVAILABLE'),
    (240,'ASP.NET MVC 4 in Action','AVAILABLE'),
    (241,'EJB 3 in Action','AVAILABLE'),
    (242,'EJB 3 in Action, Second Edition','AVAILABLE'),
    (243,'Explorer''s Guide to the Semantic Web','AVAILABLE'),
    (244,'Practical LotusScript','AVAILABLE'),
    (245,'Domino Development with Java','AVAILABLE'),
    (246,'Windows PowerShell in Action','AVAILABLE'),
    (247,'Windows PowerShell in Action, Second Edition','AVAILABLE'),
    (248,'Silverlight 4 in Action, Revised Edition','AVAILABLE'),
    (249,'Silverlight 5 in Action','AVAILABLE'),
    (250,'Hibernate Quickly','AVAILABLE'),
    (251,'Generative Art','AVAILABLE'),
    (252,'Windows Phone 7 in Action','AVAILABLE'),
    (253,'Lift in Action','AVAILABLE'),
    (254,'Web Development with Apache and Perl','AVAILABLE'),
    (255,'Real-World Functional Programming','AVAILABLE'),
    (256,'Machine Learning in Action','AVAILABLE'),
    (257,'Dependency Injection','AVAILABLE'),
    (258,'Understanding Enterprise SOA','AVAILABLE'),
    (259,'Open-Source ESBs in Action','AVAILABLE'),
    (260,'Activiti in Action','AVAILABLE'),
    (261,'DSLs in Boo: Domain-Specific Languages in .NET','AVAILABLE'),
    (262,'JUnit Recipes','AVAILABLE'),
    (263,'wxPython in Action','AVAILABLE'),
    (264,'Clojure in Action','AVAILABLE'),
    (265,'Scala in Action','AVAILABLE'),
    (266,'Working with Objects','AVAILABLE'),
    (267,'PHP in Action','AVAILABLE'),
    (269,'Secrets of the JavaScript Ninja','AVAILABLE'),
    (270,'Microsoft Office Essentials','AVAILABLE'),
    (271,'Swing','AVAILABLE'),
    (272,'Swing Second Edition','AVAILABLE'),
    (273,'The Awesome Power of Java Beans','AVAILABLE'),
    (274,'Personal Videoconferencing','AVAILABLE'),
    (275,'The Cloud at Your Service','AVAILABLE'),
    (276,'Implementing Elliptic Curve Cryptography','AVAILABLE'),
    (277,'SOA Patterns','AVAILABLE'),
    (278,'Hello World!','AVAILABLE'),
    (279,'SCBCD Exam Study Kit','AVAILABLE'),
    (280,'Portlets in Action','AVAILABLE'),
    (281,'SWT/JFace in Action','AVAILABLE'),
    (282,'OpenCL in Action','AVAILABLE'),
    (283,'Multiprotocol over ATM','AVAILABLE'),
    (284,'Dependency Injection in .NET','AVAILABLE'),
    (285,'Java 3D Programming','AVAILABLE'),
    (286,'Liferay in Action','AVAILABLE'),
    (287,'JSP Tag Libraries','AVAILABLE'),
    (289,'Instant Messaging in Java','AVAILABLE'),
    (290,'Java Applets and Channels Without Programming','AVAILABLE'),
    (291,'PowerShell in Practice','AVAILABLE'),
    (292,'PowerShell and WMI','AVAILABLE'),
    (293,'Making Sense of Java','AVAILABLE'),
    (294,'C++/CLI in Action','AVAILABLE'),
    (295,'C# in Depth','AVAILABLE'),
    (296,'C# in Depth, Second Edition','AVAILABLE'),
    (297,'Magical A-Life Avatars','AVAILABLE'),
    (298,'Becoming Agile','AVAILABLE'),
    (299,'ActiveMQ in Action','AVAILABLE'),
    (300,'Implementing PeopleSoft Financials','AVAILABLE'),
    (302,'SQL Server DMVs in Action','AVAILABLE'),
    (303,'Scala in Depth','AVAILABLE'),
    (304,'JMX in Action','AVAILABLE'),
    (305,'EJB Cookbook','AVAILABLE'),
    (306,'GWT in Action, Second Edition','AVAILABLE'),
    (307,'JUnit in Action, Second Edition','AVAILABLE'),
    (308,'Bitter Java','AVAILABLE'),
    (309,'Bitter EJB','AVAILABLE');
INSERT INTO `book` VALUES
    (310,'Spring Batch in Action','AVAILABLE'),
    (312,'JDK 1.4 Tutorial','AVAILABLE'),
    (313,'iPhone and iPad in Action','AVAILABLE'),
    (314,'SQL Server 2005 Reporting Services in Action','AVAILABLE'),
    (315,'Ten Years of UserFriendly.Org','AVAILABLE'),
    (316,'Graphics Programming with Perl','AVAILABLE'),
    (317,'RabbitMQ in Action','AVAILABLE'),
    (318,'XDoclet in Action','AVAILABLE'),
    (319,'Spring in Action','AVAILABLE'),
    (320,'Spring in Action, Second Edition','AVAILABLE'),
    (321,'Spring in Action, Third Edition','AVAILABLE'),
    (325,'Spring in Practice','AVAILABLE'),
    (327,'Java 2 Micro Edition','AVAILABLE'),
    (328,'SharePoint 2010 Workflows in Action','AVAILABLE'),
    (329,'SharePoint 2010 Web Parts in Action','AVAILABLE'),
    (330,'C++ Concurrency in Action','AVAILABLE'),
    (331,'Java Servlets by Example','AVAILABLE'),
    (332,'XML Programming with VB and ASP','AVAILABLE'),
    (334,'Oracle8i Database Administration','AVAILABLE'),
    (335,'The Engaging Web','AVAILABLE'),
    (512,'Enterprise OSGi In Action','AVAILABLE'),
    (513,'Ext JS in Action, Second Edition','AVAILABLE'),
    (514,'Android in Action, Third Edition','AVAILABLE'),
    (515,'Arduino in Action','AVAILABLE'),
    (516,'Node.js in Action','AVAILABLE'),
    (517,'Third-Party JavaScript ','AVAILABLE'),
    (519,'Multimedia Computing','AVAILABLE'),
    (520,'Web Development with JavaServer Pages','AVAILABLE'),
    (521,'Up to Speed with Swing','AVAILABLE'),
    (522,'Manager''s Guide to Open Source','AVAILABLE'),
    (523,'Programming Web Services with Java','AVAILABLE'),
    (525,'TCP/IP Programming for OS/2','AVAILABLE'),
    (530,'Implementing SAP R/3, Second Edition','AVAILABLE'),
    (531,'Implementing SAP R/3','AVAILABLE'),
    (532,'Using C-Kermit: Communication Software','AVAILABLE'),
    (533,'SCWCD Exam Study Kit','AVAILABLE'),
    (549,'Unit Testing in C++','AVAILABLE'),
    (550,'Big Data','AVAILABLE'),
    (551,'CoffeeScript in Action','AVAILABLE'),
    (559,'SQL Server MVP Deep Dives, Volume 2','AVAILABLE'),
    (560,'HTML5 in Action','AVAILABLE'),
    (562,'Java Persistence with Hibernate, Second Edition','AVAILABLE'),
    (566,'Hadoop in Practice','AVAILABLE'),
    (569,'HBase in Action','AVAILABLE'),
    (571,'Flex Mobile in Action','AVAILABLE'),
    (577,'HTML5 for .NET Developers','AVAILABLE'),
    (580,'50 Android Hacks','AVAILABLE'),
    (591,'PowerShell in Depth','AVAILABLE'),
    (599,'Augmented Reality Revealed','AVAILABLE'),
    (607,'Building Well-Structured JavaScript Applications','AVAILABLE'),
    (611,'Linked Data','AVAILABLE'),
    (620,'Mule in Action, Second Edition','AVAILABLE'),
    (624,'Single Page Web Applications','AVAILABLE'),
    (628,'The Art of Unit Testing, Second Edition','AVAILABLE'),
    (629,'Play for Java','AVAILABLE'),
    (631,'Hello World! Second Edition','AVAILABLE'),
    (632,'Dart in Action','AVAILABLE'),
    (634,'Redis in Action','AVAILABLE'),
    (636,'Using the TI-83 Plus/TI-84 Plus','AVAILABLE'),
    (637,'Neo4j in Action','AVAILABLE'),
    (639,'Programming the TI-83 Plus/TI-84 Plus','AVAILABLE'),
    (640,'Functional Programming in Scala','AVAILABLE'),
    (641,'Play for Scala','AVAILABLE'),
    (642,'Node.js in Practice','AVAILABLE'),
    (643,'SonarQube in Action','AVAILABLE'),
    (644,'Windows Store App Development: C# and XAML','AVAILABLE'),
    (645,'Learn Windows IIS in a Month of Lunches','AVAILABLE'),
    (646,'Mondrian in Action','AVAILABLE'),
    (648,'RabbitMQ in Depth','AVAILABLE'),
    (649,'Akka in Action','AVAILABLE'),
    (650,'Extending jQuery','AVAILABLE'),
    (651,'OCA Java SE 7 Programmer I Certification Guide','AVAILABLE'),
    (652,'Kanban in Action','AVAILABLE'),
    (653,'Solr in Action','AVAILABLE'),
    (655,'Making Sense of NoSQL','AVAILABLE'),
    (656,'Jaguar Development with PowerBuilder 7','AVAILABLE'),
    (657,'Grails in Action, Second Edition','AVAILABLE'),
    (658,'Rails 4 in Action','AVAILABLE'),
    (659,'Learn Windows PowerShell in a Month of Lunches, Second Edition','AVAILABLE'),
    (662,'AOP in .NET','AVAILABLE'),
    (663,'Learn PowerShell Toolmaking in a Month of Lunches','AVAILABLE'),
    (664,'CMIS and Apache Chemistry in Action','AVAILABLE'),
    (667,'Action Guide (aka VB .NET)','AVAILABLE'),
    (670,'Learn Active Directory Management in a Month of Lunches','AVAILABLE'),
    (671,'Spring in Action, Fourth Edition','AVAILABLE'),
    (672,'The Mikado Method','AVAILABLE'),
    (676,'The Responsive Web','AVAILABLE'),
    (677,'Fast ASP.NET Websites','AVAILABLE'),
    (678,'SBT in Action','AVAILABLE'),
    (679,'PowerShell Deep Dives','AVAILABLE'),
    (680,'Gradle in Action','AVAILABLE'),
    (681,'Scalatra in Action','AVAILABLE'),
    (683,'AngularJS in Action','AVAILABLE'),
    (684,'Software Development Metrics','AVAILABLE'),
    (685,'F# Deep Dives','AVAILABLE'),
    (686,'C# in Depth, Third Edition','AVAILABLE'),
    (688,'PostGIS in Action, Second Edition','AVAILABLE'),
    (689,'R in Action, Second Edition','AVAILABLE'),
    (691,'The Joy of Clojure, Second Edition','AVAILABLE'),
    (692,'iOS 7 in Action','AVAILABLE'),
    (693,'Hello App Inventor!','AVAILABLE'),
    (696,'Ember.js in Action','AVAILABLE'),
    (697,'Netty in Action','AVAILABLE'),
    (699,'RavenDB in Action','AVAILABLE'),
    (700,'OCP Java SE 7 Programmer II Certification Guide','AVAILABLE'),
    (702,'Backbone.js in Action','AVAILABLE'),
    (703,'Clojure in Action, Second Edition','AVAILABLE'),
    (706,'Practical Data Science with R','AVAILABLE'),
    (707,'Secrets of the JavaScript Ninja pBook upgrade','AVAILABLE'),
    (711,'ArcGIS Web Development','AVAILABLE'),
    (712,'Elasticsearch in Action','AVAILABLE'),
    (716,'Learn SCCM 2012 in a Month of Lunches','AVAILABLE'),
    (717,'Programming for Musicians and Digital Artists','AVAILABLE'),
    (719,'BDD in Action','AVAILABLE'),
    (723,'Windows Phone 8 in Action','AVAILABLE'),
    (724,'Titanium Alloy in Action','AVAILABLE'),
    (727,'Giraph in Action','AVAILABLE'),
    (728,'The Well-Grounded Rubyist, Second Edition','AVAILABLE'),
    (729,'Go in Action','AVAILABLE'),
    (731,'The Programmer''s Guide to Apache Thrift ','AVAILABLE'),
    (732,'Grokking Functional Programming','AVAILABLE'),
    (733,'CORS in Action','AVAILABLE'),
    (736,'Reactive Design Patterns','AVAILABLE'),
    (740,'Storm Applied','AVAILABLE'),
    (743,'Real-World Machine Learning','AVAILABLE'),
    (744,'jQuery UI in Action','AVAILABLE'),
    (746,'Web Components in Action','AVAILABLE'),
    (748,'JavaScript Application Design','AVAILABLE'),
    (749,'Git in Practice','AVAILABLE'),
    (750,'Impala in Action','AVAILABLE'),
    (751,'Java 8 in Action','AVAILABLE'),
    (753,'Elixir in Action','AVAILABLE'),
    (755,'MongoDB in Action, Second Edition','AVAILABLE'),
    (757,'Getting MEAN with Mongo, Express, Angular, and Node','AVAILABLE'),
    (761,'jQuery in Action, Third Edition','AVAILABLE'),
    (764,'D3.js in Action','AVAILABLE'),
    (765,'Learn SQL Server Administration in a Month of Lunches','AVAILABLE'),
    (766,'Geoprocessing with Python','AVAILABLE'),
    (767,'Barcodes with iOS','AVAILABLE'),
    (771,'Chef in Action','AVAILABLE'),
    (772,'Hadoop in Practice, Second Edition','AVAILABLE'),
    (774,'Oculus Rift in Action','AVAILABLE'),
    (776,'OpenStack in Action','AVAILABLE'),
    (777,'PowerShell in Depth, Second Edition','AVAILABLE'),
    (785,'Practical Probabilistic Programming','AVAILABLE'),
    (786,'Unity in Action','AVAILABLE'),
    (794,'Express.js in Action','AVAILABLE'),
    (795,'Learn Git in a Month of Lunches','AVAILABLE'),
    (796,'Understanding SPAs','AVAILABLE');
